import { useState } from "react";
import axios from "axios";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Features from "../components/Features";
import ProductList from "../components/ProductList";
import AddProductBtn from "../components/AddProductBtn";
import AddPanel from "../components/AddPanel";

export default function Home({ productList, admin }) {
  const [close, setClose] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>SNEAKER SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/air.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Features />
      {admin && <AddProductBtn setClose={setClose} />}
      <ProductList productList={productList} />
      {!close && <AddPanel setClose={setClose} />}
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies ?? "";
  let admin = false;
  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }

  const res = await axios.get("http://localhost:3000/api/products");

  return {
    props: {
      productList: res.data,
      admin,
    },
  };
};
